In [15]:
import datetime
tanggal_hari_ini = str (datetime.date.today())
aList =["Darren Alfarrel Syawalulail",2022071011, "Informatika", "Desain dan Analisis Algoritma",tanggal_hari_ini, "Univeritas pembangunan Jaya"]
print(aList)

['Darren Alfarrel Syawalulail', 2022071011, 'Informatika', 'Desain dan Analisis Algoritma', '2023-09-13', 'Univeritas pembangunan Jaya']


In [18]:
bin_colors=['White','Green','Blue','Black','Red']
bin_colors[2]

'Blue'

In [19]:
print(aList[5])

Univeritas pembangunan Jaya


In [20]:
print(aList[1])

2022071011


In [28]:
bin_colors[0:2]

['White', 'Green']

In [26]:
aList[1:3]

[2022071011, 'Informatika']

In [35]:
for aColor in bin_colors:
  	print(aColor + " Square")

White Square
Green Square
Blue Square
Black Square
Red Square


In [41]:
for dataMahasiswa in aList:
    print(dataMahasiswa , "square")

Darren Alfarrel Syawalulail square
2022071011 square
Informatika square
Desain dan Analisis Algoritma square
2023-09-13 square
Univeritas pembangunan Jaya square


In [40]:
for dataMahasiswa in aList:
    print("UPJ" , dataMahasiswa)

UPJ Darren Alfarrel Syawalulail
UPJ 2022071011
UPJ Informatika
UPJ Desain dan Analisis Algoritma
UPJ 2023-09-13
UPJ Univeritas pembangunan Jaya


In [44]:
bin_colors[1]

'Green'

In [46]:
bin_colors[0:]

['White', 'Green', 'Blue', 'Black', 'Red']

In [50]:
bin_UPJ=["Universitas","Pembangunan","Jaya"]
bin_UPJ

['Universitas', 'Pembangunan', 'Jaya']

In [52]:
hariAwal = ("senin", "selasa","rabu")
hariAkhir = ("kamis", "jumat", "sabtu")
hari = (hariAwal, hariAkhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [53]:
#Nested Tuple
nested_tuple = ([100],[200,400,600],[300],[400,800])
print(nested_tuple)

([100], [200, 400, 600], [300], [400, 800])


In [54]:
bin_colors ={
"manual_color": "Yellow",
"approved_color": "Green",
"refused_color": "Red"}

print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [55]:
latihan={
    "Nama":"Darren Alfarrel Syawalulail",
    "NIM":"2022071011",
    "Prodi":"Informatika",
    "Universitas":"UPJ"
}
print(latihan)

{'Nama': 'Darren Alfarrel Syawalulail', 'NIM': '2022071011', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [62]:
#Inisiasi Set
set_01 = {4,5,6,2}
print("set_01 = ", set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])

print(type(set_02))
print("set_03 = ", set_03)

print("\nmenambah")
set_01.add(576)
print(set_01)

print("\nmenghapus")
set_01.discard(6)
print(set_01)

print("\nunion")
print(set_01|set_03)

print("\nintersection")
print(set_01&set_03)

print("\ndifference")
print(set_01-set_03)

print("\nsymmetric difference")
print(set_01^set_03)

set_01 =  {2, 4, 5, 6}
<class 'set'>
set_03 =  {1, 2, 3, 4}

menambah
{576, 2, 4, 5, 6}

menghapus
{576, 2, 4, 5}

union
{576, 1, 2, 3, 4, 5}

intersection
{2, 4}

difference
{576, 5}

symmetric difference
{576, 1, 3, 5}


In [56]:
yellow = {'dandelions','leaves','fire hydrant'}
red = {'rose','blood','leaves','fire hydrant'}
print(yellow|red)
print(yellow&red)

{'fire hydrant', 'dandelions', 'rose', 'blood', 'leaves'}
{'fire hydrant', 'leaves'}


In [60]:
import pandas as pd

df = pd.DataFrame([
    [1, "Informatika", 50, 30, 20],
    [2, "Sistem Informasi", 55, 30, 25],
    [3, "Teknik Sipil", 40, 30, 10]
])

df.columns = ["No", "Prodi", "Mahasiswa", "laki-laki", "Perempuan"]
df.style.hide(axis='index')

In [61]:
import numpy as np

matrix = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
    ])

print(matrix)

print("\nTranspose:")
print(matrix.T)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
